apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: waterwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yasser2003/waterwise-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/waterwise
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: waterwise
spec:
  type: NodePort
  selector:
    app: backend
  ports: 
    - port: 8080         # ClusterIP port
      targetPort: 8080   # Pod port
      nodePort: 30080
