apiVersion: apps/v1
kind: Deployment
metadata:
  name: waterwise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterwise-backend
  template:
    metadata:
      labels:
        app: waterwise-backend
    spec:
      containers:
      - name: backend
        image: waterwise_app-backend:latest # Pense à builder et tagger cette image localement !
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/waterwise"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: waterwise-backend-service
spec:
  selector:
    app: waterwise-backend
  ports:
  - protocol: TCP
    port: 8081         # Port externe que tu peux utiliser pour accéder au backend
    targetPort: 8080   # Port du container exposé par le backend
  type: NodePort
