apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: waterwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yasser2003/waterwise-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: http://backend-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: waterwise
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 80
  type: NodePort
