version: '3.8'

services:
  backend:
    build: .
    container_name: waterwise-backend
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/waterwise
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - waterwise-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    #ports:
      #- "3306:3306"
    environment:
      MYSQL_DATABASE: waterwise
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - waterwise-net

volumes:
  mysql_data:

networks:
  waterwise-net:
