pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS = 'dockerhub-creds'  
    BACKEND_IMAGE         = 'yasser2003/waterwise-backend'
    FRONTEND_IMAGE        = 'yasser2003/waterwise-frontend'
  }
  stages {

    stage('Tests') {
      steps {
        dir('WaterWise_app') {
          sh '''
            rm -rf target
            ls
            docker run --rm -v /var/jenkins_home/workspace/react-pipeline-1/WaterWise_app:/app -w /app \
              --user root \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/water_wise \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=password0664938616 \
              maven:3.9.4-eclipse-temurin-21 mvn test
          '''
        }
      }
    }


    stage('Docker Login') {
      steps {
        withCredentials([usernamePassword(credentialsId: env.DOCKERHUB_CREDENTIALS, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
        }
      }
    }

    stage('Build & Push') {
      steps {
        dir('WaterWise_app') {
          // 1) build both services
          sh 'docker compose build --pull'

          // 2) push them up by service name
          sh 'docker compose push backend'
          sh 'docker compose push frontend'
        }
      }
    }
    
    stage('Cleanup') {
      steps {
        sh 'docker logout'
        sh 'docker rmi yourdockerhubuser/waterwise-backend:latest yourdockerhubuser/waterwise-frontend:latest || true'
      }
    }
  }

  post {
    always {
      echo 'Pipeline finished.'
    }
    failure {
      echo 'One or more stages failed.'
    }
  }
}
