pipeline {
    tools { nodejs "node" }
    agent { label 'jenkins-agent-1' }
    environment{
        dockerImage=''
    }
    stages {
        stage('Build') {
            steps {
                echo 'This is the build stage'
                sh '''
                cd WaterWise_app/react-frontend
                npm install
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'This is the test stage'
                echo 'i am testing the node version'
                sh 'node -v'
                echo 'running tests'
                sh '''
                cd WaterWise_app/react-frontend
                npm run test
                '''
                echo 'i am testing the docker version'
                sh 'docker -v'
            }
        }

        stage("Building Image") {
            steps {
                sh '''
                    cd WaterWise_app/react-frontend
                    docker build -t yasser2003/plat-dev-images:${BUILD_NUMBER} .
                '''
            }
        }

        stage("Deploy Image") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        cd WaterWise_app/react-frontend
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push yasser2003/plat-dev-images:${BUILD_NUMBER}
                        docker logout
                    '''
                }
            }
        }
    }
}
