name : DevSecOps pipeline

on : 
  push:

env:
  BUILD_ARTIFACT_NAME: build-artifacts
  DOCKER_IMAGE_NAME: waterwise-backend

jobs :
  # 1) checkout, build, run unit tests, upload build artifacts
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      artifact_uploaded: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run unit tests (Maven)
        working-directory: backend
        run: |
          chmod +x mvnw
          ./mvnw -B test

      - name: Package backend (skip tests)
        working-directory: backend
        run: |
          ./mvnw -B -DskipTests package

      - name: Collect build artifacts
        run: |
          mkdir -p ./ci_artifacts/backend
          cp ${GITHUB_WORKSPACE}/backend/target/*.jar ./ci_artifacts/backend/ || true
          # include any other files you want preserved (e.g. config, compiled resources)
          ls -la ./ci_artifacts || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ./ci_artifacts

  # 2) SCA scan with Snyk (checkout build artifacts, run Snyk against pom.xml then upload results)
  sca-snyk:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}

      - name: Make mvnw executable (important)
        run: chmod +x ./backend/mvnw

      - name: Setup Node (for Snyk CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN || true

      - name: Run Snyk SCA (backend - Maven)
        working-directory: backend
        run: |
          # run Snyk test on the backend pom (output json to file)
          snyk test --file=pom.xml --json > "${{ github.workspace }}/snyk-backend-result.json" || true

          # verify the report
          ls -la "${{ github.workspace }}/snyk-backend-result.json"

      - name: Upload Snyk results
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: snyk-backend-result.json

# 3) SAST scan Manual build if autobuild doesn't work
  sast-codeql:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Manual Build
        working-directory: backend
        run: |
          chmod +x mvnw
          ./mvnw clean compile -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"
          output: sarif-results
          upload: false

      - name: Upload CodeQL SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif
          path: sarif-results/java.sarif

  # 4) Build the docker image and push it to Docker Hub
  build-and-push-image:
    needs: [sca-snyk, sast-codeql]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        working-directory: backend
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          echo "Building image $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" -f Dockerfile .
          docker tag "$IMAGE_TAG" ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Push images to Docker Hub
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker push "$IMAGE_TAG"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Write pushed image info
        run: |
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}" > pushed-image.txt
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest" >> pushed-image.txt
          cat pushed-image.txt

      - name: Upload pushed image info
        uses: actions/upload-artifact@v4
        with:
          name: pushed-image-info
          path: pushed-image.txt
          
# 5) Pull the docker images (backend + mysql), start containers, run DAST with OWASP ZAP, upload results, clean up
  dast-owasp-zap:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download pushed image info
        uses: actions/download-artifact@v4
        with:
          name: pushed-image-info
          path: ./

      - name: Read pushed image name
        id: read_image
        run: |
          IMAGE=$(head -n 1 pushed-image.txt)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Pull images
        run: |
          docker pull "${{ steps.read_image.outputs.image }}"
          docker pull mysql:8.0

      - name: Create docker network
        run: docker network create devsecops-test-net

      - name: Start MySQL container
        run: |
          docker run -d \
            --name mysql-dev \
            --network devsecops-test-net \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=waterwise \
            mysql:8.0
          
          echo "Waiting for MySQL..."
          sleep 20

      - name: Start backend container
        run: |
          docker run -d \
            --name backend-dev \
            --network devsecops-test-net \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dev:3306/waterwise \
            -e SPRING_DATASOURCE_USERNAME=root \
            -e SPRING_DATASOURCE_PASSWORD=root \
            -e SPRING_JPA_HIBERNATE_DDL_AUTO=update \
            ${{ steps.read_image.outputs.image }}
          
          echo "Waiting for backend..."
          sleep 30

      - name: Run OWASP ZAP baseline scan
        run: |
          mkdir -p zap-output
          docker run --rm \
            --network devsecops-test-net \
            -v "${{ github.workspace }}/zap-output:/zap/wrk:rw" \
            owasp/zap2docker-stable \
            zap-baseline.py \
            -t http://backend-dev:8080 \
            -r zap-report.html \
            -J zap-report.json || true

      - name: Upload DAST reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dast-zap-reports
          path: zap-output/

      - name: Cleanup
        if: always()
        run: |
          docker rm -f backend-dev mysql-dev || true
          docker network rm devsecops-test-net || true